### ISSUE TITLE
Black Background when inactive

### ISSUE THREAD

**Issue by poochie89** [sourcechord/FluentWPF#103] opened 2021-03-08 07:23 UTC
When the Window is inactive the Window shows a black background.

**Comment by sourcechord** [comment] 2021-03-09 16:19
Hi, @poochie89

This is by design, and same as the acrylic behavior in UWP apps.
### Workaround
You can customize Fallback color with `FallbackColor` property.
Please try the following code.
```xml
<fw:AcrylicWindow x:Class="FluentWPFSample.Views.AcrylicWindow"
                  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                  xmlns:fw="clr-namespace:SourceChord.FluentWPF;assembly=FluentWPF"
                  xmlns:local="clr-namespace:FluentWPFSample.Views"
                  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                  Title="AcrylicWindow"
                  FallbackColor="Transparent"
                  Width="300"
                  Height="300"
                  mc:Ignorable="d">
    <Grid Background="#70FFFFFF">
        <TextBlock Margin="10"
                   HorizontalAlignment="Left"
                   VerticalAlignment="Top"
                   Text="This is AcrylicWindow"
                   TextWrapping="Wrap" />
    </Grid>
</fw:AcrylicWindow>
```

**Comment by sourcechord** [comment] 2021-03-26 14:28
I'll close this issue.
If you have any problems, please reopen this issue.

**Closed by sourcechord** 2021-03-26 14:28 UTC
