### ISSUE TITLE
Insider build 21327 issue

### ISSUE THREAD

**Issue by milos12345** [sourcechord/FluentWPF#104] opened 2021-03-09 16:28 UTC
This was not tested by me but one user reported that when my program with FluentWPF is open "when trying to move any window, they move with a delay like slow motion". I've asked him to try it with FluentWPF sample app and he reported the same problem. Started happening right after update to W10 to insider build 21327.

**Comment by madninjaskillz** [comment] 2021-03-14 20:14
I'm experiencing something similar - when running my app, if Acrylic is on, the my 4k display has some weird issues, but my other screen (@1080p) is fine. we are talking super slow motion mouse movement etc. easy to reproduce, a pain to diagnose. I'm looking into the issue see if i can get any work arounds but am pulling my hair out. I guess rolling back on windows update is an option - but it might just be delaying the issue.

**Comment by madninjaskillz** [comment] 2021-03-14 23:32
submitted a PR that resolves this - however, i can reproduce it without a FluentWPF app too - the preview on tasks in the taskbar can cause it too.

**Comment by sourcechord** [comment] 2021-03-26 13:26
Hi @milos12345 and @madninjaskillz 
Thanks for the information.

I'll try it when next insider preveiw released.
(Currently, the latest windows10 iso is 21286)
If the problem still occurs, I'd like to inspect this issue.

Please wait for a while.

**Comment by milos12345** [comment] 2021-08-01 03:08
I have tested it now with Windows 11 - 21H2 build 22000.100 and the issue is still there

**Comment by milos12345** [comment] 2021-08-01 17:48
This is how it looks on Win 11 (official dev build 22000.100 ) the latest alpha of FluentWPF. 
- Same lag regardless of the blur effect type.

![Win11AcrylicEffectLag-optim](https://user-images.githubusercontent.com/5231547/127780498-2851f05f-d401-4f55-8051-0a780f611da5.gif)

The lag happens if there is anything behind the window (on clean desktop the lag is not noticeable)
Another issue is that blur effect is shown only on move, while the window is opaque otherwise. I think it would be fine if `fw:AcrylicWindow.Enabled="False"` was while window was being moved/resized, and restored once mouse is released.

**Comment by sourcechord** [comment] 2021-08-13 04:55
Hi there.
Currently Windows11 seems that doesn't support acrylic effect with SetWindowCompositionAttribute API. So that,  I turnd off acrylic effect in FluentWPF 0.10.0.  
See also(#130, [#42](https://github.com/sourcechord/FluentWPF/issues/42#issuecomment-891954225))

I'll close this issue, and track the problems about acrylic effect in #130.

**Closed by sourcechord** 2021-08-13 04:55 UTC

**Comment by fhnb16** [comment] 2021-08-19 12:32
@milos12345 video-drivers installed in your system? I asking because window borders are squared.
Blur problems can be of the same "nature"
