### ISSUE TITLE
Acryle brush doesn't wotk in 0.2.0 or higher version. 

### ISSUE THREAD

**Issue by EugenyTsoy** [sourcechord/FluentWPF#10] opened 2018-05-20 20:46 UTC
Hi Sourcehord,
There is some problem with AcrylicBrush in version 0.2.0 or higher:
![image](https://user-images.githubusercontent.com/7031776/40283472-468ef588-5c98-11e8-90b3-01308bb6f10a.png)
I checked it in version 0.1.0, and it works:
![image](https://user-images.githubusercontent.com/7031776/40283502-89d38214-5c98-11e8-8fa6-6843ee7c1654.png)

**Comment by sourcechord** [comment] 2019-06-04 14:26
I'll close this issue.
If these problems continue to occur, please reopen this issue.

**Comment by ammar-mik** [comment] 2021-03-25 07:59
I am getting the exact same issue as mentioned above. It is easily reproducible if I start a new WPF project from the Visual Studio template, and follow the instructions from the [readme](https://github.com/sourcechord/FluentWPF#acrylicbrush)

<img width="314" alt="Screenshot 2021-03-24 at 16 08 25" src="https://user-images.githubusercontent.com/70579255/112438522-49305c80-8d48-11eb-88db-e69e4b8fdc35.png">

However, if I clone this repository and run the samples, then the brush works fine.

**Comment by sourcechord** [comment] 2021-03-26 12:50
Hi @ammar-mik 
Thanks for the information.
Now, I understand this issue by hearing your feedback.

AcrylicBrush coldn't render correctly when the owener doesn't have Width and Height properties.
## OK
```xml
        <Rectangle Grid.ColumnSpan="2"
                   Width="200" Height="200"
                   Fill="{fw:AcrylicBrush grid}"
                   Stroke="Black"/>
```
## NG
```xml
        <Rectangle Grid.ColumnSpan="2"
                   Fill="{fw:AcrylicBrush grid}"
                   Stroke="Black"/>
```

I found the cause of this issue. I'll fix it in next update.

**Comment by ammar-mik** [comment] 2021-03-29 08:37
Thanks mate. I'll try it out with the Width and Height properties before the fix is out.

**Comment by sourcechord** [comment] 2021-08-13 02:30
It was supported in FluentWPF 0.10.0.
I'll close this issue. If there are any problems, please reopen this issue.

**Closed by sourcechord** 2021-08-13 02:30 UTC
Labels: bug
